import org.jetbrains.compose.desktop.application.dsl.TargetFormat

// Part I — the JARVIS desktop client (Compose for Desktop).
//
// A module ADDED beside `:app`; the Android build does not know it exists. The
// Kotlin Gradle plugin is already on the root classpath (AGP 9 bundles KGP 2.2.10),
// which is why `kotlin.jvm` is applied here without a version.
plugins {
    id("org.jetbrains.kotlin.jvm")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.compose")
}

// ---------------------------------------------------------------------------
// Shared code, WITHOUT moving it.
//
// The Android-free logic is compiled straight from `app/src/main` — the same trick
// scripts/jvmcheck uses — so the phone app's files stay exactly where they are and
// the Android build cannot be broken by this module. The later `:shared` KMP module
// (EXECUTION_PLAN Part I, step 5) replaces this list; until then it is the seam.
//
// Rule for this list: a file may be added ONLY if it imports nothing from
// android/androidx. The handful of Android objects these files call —
// `BuildConfig`, `Identity`, `UsageStats` — have desktop versions with the same
// names and signatures in this module (see src/main/kotlin/com/jarvis/os).
// ---------------------------------------------------------------------------
val appMain: File = rootProject.file("app/src/main/java")
val SHARED_FROM_APP = listOf(
    "com/jarvis/os/data/ChatTurn.kt",
    "com/jarvis/os/data/MemoryActions.kt",
    "com/jarvis/os/assistant/Markers.kt",
    "com/jarvis/os/memory/MemoryFormat.kt",
    "com/jarvis/os/debug/DebugLog.kt",
    // The Worker client, byte-for-byte the one the phone ships.
    "com/jarvis/os/ai/ProxyClient.kt",
    "com/jarvis/os/ai/GroqClient.kt",
    "com/jarvis/os/ai/ModelRouter.kt",
    "com/jarvis/os/ai/RateLimit.kt",
    "com/jarvis/os/ai/SystemPrompt.kt",
)

val sharedSrcDir = layout.buildDirectory.dir("generated/sharedFromApp")
val syncSharedFromApp by tasks.registering(Sync::class) {
    from(appMain) { SHARED_FROM_APP.forEach { include(it) } }
    into(sharedSrcDir)
}

// ---------------------------------------------------------------------------
// Build config — the same inputs, from the same places, as app/build.gradle.kts:
// a Gradle property (e.g. ~/.gradle/gradle.properties) or an environment variable
// (CI secrets). NEVER committed: this is generated into build/, which is ignored.
// ---------------------------------------------------------------------------
fun prop(name: String): String =
    (project.findProperty(name) as String?)?.takeIf { it.isNotBlank() }
        ?: System.getenv(name)?.takeIf { it.isNotBlank() }
        ?: ""

val configValues: Map<String, String> = mapOf(
    "WORKER_URL" to prop("WORKER_URL").ifBlank { "https://superfoodapp.goformanoj.workers.dev" },
    "PROXY_SECRET" to prop("PROXY_SECRET"),
    // Named FIREBASE_WEB_API_KEY as an input (like the app), FIREBASE_API_KEY in code.
    "FIREBASE_API_KEY" to prop("FIREBASE_WEB_API_KEY"),
    "GROQ_API_KEY" to prop("GROQ_API_KEY"),
    "GEMINI_API_KEY" to prop("GEMINI_API_KEY"),
    "GOOGLE_WEB_CLIENT_ID" to prop("GOOGLE_WEB_CLIENT_ID"),
    "VERSION_NAME" to prop("VERSION_NAME").ifBlank { "0.1.0" },
)

val configDir = layout.buildDirectory.dir("generated/desktopConfig")
val generateBuildConfig by tasks.registering {
    // Values are inputs so a changed secret regenerates the file; they are never logged.
    inputs.properties(configValues)
    outputs.dir(configDir)
    doLast {
        fun lit(v: String) = "\"" + v.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$") + "\""
        val body = configValues.entries.joinToString("\n") { (k, v) -> "    const val $k: String = ${lit(v)}" }
        val out = configDir.get().file("com/jarvis/os/BuildConfig.kt").asFile
        out.parentFile.mkdirs()
        out.writeText(
            "package com.jarvis.os\n\n" +
                "// GENERATED by desktop/build.gradle.kts — do not edit, never commit.\n" +
                "object BuildConfig {\n    const val DEBUG: Boolean = true\n$body\n}\n",
        )
    }
}

sourceSets {
    main {
        kotlin.srcDir(syncSharedFromApp)
        kotlin.srcDir(generateBuildConfig)
    }
}

kotlin {
    compilerOptions {
        // CI builds on JDK 17; the laptop runs Android Studio's JBR 21. Target 17 for both.
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation(compose.desktop.currentOs)
    implementation(compose.material3)
    implementation(compose.materialIconsExtended)
    // Dispatchers.Main on desktop is the Swing EDT.
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.10.2")
    // org.json ships inside Android; on the JVM it is this artifact, same API —
    // which is what lets ProxyClient/GroqClient compile here unchanged.
    implementation("org.json:json:20250517")

    testImplementation("junit:junit:4.13.2")
}

tasks.test {
    useJUnit()
}

// `./gradlew :desktop:ping` — health check of the server path (see Ping.kt).
tasks.register<JavaExec>("ping") {
    group = "verification"
    description = "Sends the tiny OK probe to the Worker through the real client."
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("com.jarvis.os.desktop.PingKt")
}

compose.desktop {
    application {
        mainClass = "com.jarvis.os.desktop.MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Msi, TargetFormat.Exe)
            packageName = "JARVIS"
            packageVersion = "1.0.0"
            description = "JARVIS OS — desktop"
            vendor = "JARVIS OS"
            windows {
                menuGroup = "JARVIS"
                shortcut = true
                // Stable id so an upgrade replaces the install instead of adding a second one.
                upgradeUuid = "6f3c1f2e-8a4b-4c7e-9d2a-5b1e0c9a7d41"
            }
        }
    }
}
